[project]
name = "discord-research-assistance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dependency-injector>=4.49.0",
    "discord-py>=2.7.1",
    "groq>=1.4.0",
    "httpx>=0.28.1",
    "playwright>=1.60.0",
    "pydantic-settings>=2.14.1",
    "pymupdf4llm>=1.27.2.3",
    "python-dotenv>=1.2.2",
]
